services:
  evolution-api:
    hostname: prismasyncv2
    container_name: evolution_api
    environment:
      - NODE_OPTIONS=--max-old-space-size=2048
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - evolution-net
    depends_on:
      rabbitmq:
        condition: service_started
      redis:
        condition: service_started
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == evolution-manager
  nginx:
    image: jc21/nginx-proxy-manager:latest
    hostname: prismasyncv2
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - nginx_data:/data
      - nginx_letsencrypt:/etc/letsencrypt
    networks:
      - evolution-net

  # portainer:
  #   container_name: portainer
  #   hostname: prismasyncv2
  #   image: portainer/portainer-ce:latest
  #   restart: always
  #   ports:
  #     - "9000:9000"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - portainer_data:/data
  #   networks:
  #     - evolution-net

  postgres:
    container_name: postgres
    hostname: prismasyncv2
    image: postgres:15
    command: ["postgres", "-c", "max_connections=1000"]
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - evolution-net

  redis:
    image: redis:alpine
    hostname: prismasyncv2
    container_name: redis
    restart: always
    command: >
      redis-server --port 6379 --appendonly yes --requirepass "$REDIS_PASSWORD"
    env_file: .env
    volumes:
      - /data/redis:/data
      - evolution_redis:/data
    ports:
      - "6379:6379"
    networks:
      - evolution-net
  rabbitmq:
    container_name: rabbitmq
    hostname: prismasyncv2
    image: rabbitmq:management
    restart: always
    environment:
      - RABBITMQ_ERLANG_COOKIE=33H2CdkzF5WrnJ4ud6nkUdRTKXvbCHeFjvVL71p
      - RABBITMQ_DEFAULT_VHOST=default
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
    # healthcheck:
    #   test: curl --fail http://localhost:15672/ || exit 1
    #   interval: 40s
    #   timeout: 30s
    #   retries: 3
    #   start_period: 60s
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - evolution-net

volumes:
  evolution_instances:
  portainer_data:
  postgres_data:
  pgadmin_data:
  evolution_redis:
  rabbitmq_data:
  nginx_data:
  nginx_letsencrypt:

networks:
  evolution-net:
    name: evolution-net
    driver: bridge
